# # Site settings
# title: A blog about lorem ipsum dolor sit amet
# description: A blog about lorem ipsum dolor sit amet
# # baseurl: "/particle" # the subpath of your site, e.g. /blog
# # url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# General Information
user:
  name: Brady Walsh
  title: IT Networking Professional
  email: knighthawk0192@gmail.com
  twitter: knighthawkbro
  github: knighthawkbro
  linkedin: brady-walsh-3a81593b

description: TODO

# About you
about:
  title: About me
  description: >
    I am an IT professional with over 7 years of experience. I am also a student
    of Wentworth Institute of Technology focusing on Network Administration. I
    enjoy programming, playing video games, traveling, and spending time with my
    family.

# Your projects
project_section:
  title: Featured Projects
  projects:
    - name: Website for Joanna Shea O'Brien
      description: >
        Small, single page website I created for my friend in 2017.
      featured_skills: HTML5, CSS3, and JS
      featured_image: "assets/img/jso.png"
      url: http://www.joannasheaobrien.com
      leftAligned: true
    - name: In The Cloud - Senior Project - BSCN Wentworth
      description: >
        Developed a Citrix solution in the cloud for outsourcing networking
        infrastructure in AWS.
      featured_skills: AWS, VPNs, pfSense
      featured_image: assets/img/inthecloud.jpg
      url: assets/media/seniorprojectpresentation.pdf
      leftAligned: false


########ADVANCE##############
# Google-analytics
google-analytics:
  id: "UA-109150226-1"


exclude:
  - 'package.json'
  - 'src'
  - 'node_modules'
  - '.DS_Store'
