# # Site settings
# title: A blog about lorem ipsum dolor sit amet
# description: A blog about lorem ipsum dolor sit amet
# # baseurl: "/particle" # the subpath of your site, e.g. /blog
# # url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# General Information
paginate: 6
paginate_path: "/blog/page:num"
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# url: "http://bradywalsh.me"


user:
  name: Brady Walsh
  title: IT Networking Professional
  email: knighthawk0192@gmail.com
  twitter: knighthawkbro
  github: knighthawkbro
  linkedin: bradywalsh92

description: >
  Brady Walsh is a self-motivated and organized professional with 9 years of 
  experience providing thorough and skillful technical support for a small-to-large-scale 
  companies. Creative problem solver with the ability to think outside the box and 
  effectively resolve technical challenges. Uniquely able to learn new skills 
  and quickly adapt to the ever-changing IT industry.

# About you
about:
  title: About me
  description: >
    I am an IT networking professional with over 9 years of experience. I graduated from
    Wentworth Institute of Technology with a degree focusing on Network Administration. I
    currently offering IT consulting services. I enjoy programming, playing video games, 
    traveling, and spending time with my family.

# Your projects
project_section:
  title: Featured Projects
  projects:
    - name: Website for Joanna Shea O'Brien
      description: >
        Small, single page website I created for my friend in 2017. Written
        in HTML5, SASS, and Coffee Script. Hosted on GitHub pages with Jekyll
        as the frontend.
      featured_skills: HTML5, CSS3, and JS
      featured_image: "assets/img/jso.png"
      url: https://www.joannasheaobrien.com
      leftAligned: true
    - name: In The Cloud - Senior Project - BSCN Wentworth
      description: >
        Developed a Citrix solution in the cloud for outsourcing networking
        infrastructure in AWS. Built with $0 dollars for a budget. Seemless
        integration into a client's environment via point-to-point VPN and
        DNS.
      featured_skills: AWS, VPNs, pfSense
      featured_image: assets/img/inthecloud.jpg
      url: assets/media/seniorprojectpresentation.pdf
      leftAligned: false
    - name: My Blog
      description: >
        Started up a blog for my Software Engineering class. Blog post come
        whenever I feel like writing. Mostly aimed at life, work, and 
        technical interests.
      featured_skills: HTML5, CSS3, JS, Technical Writing
      featured_image: assets/img/blog.png
      url: blog
      leftAligned: true

# TODO: Might be a good idea to get Client testimonials

########ADVANCE##############
# Google-analytics
google-analytics:
  id: "UA-109150226-1"

exclude:
  - 'package.json'
  - 'src'
  - 'node_modules'
  - '.DS_Store'
  - 'bower_components'

disqus:
  shortname: bradywalsh
